### ISSUE TITLE
Cache files get deleted after new run

### ISSUE THREAD

**Issue by kraw-ios** [raulriera/Cacher#9]
@raulriera Hello,

Cache files are deleted after the application is run again, but during application execution it is able to get the cache properly from the directory.

Do you know what it can be? because it’s strange that he’s able to fetch during runtime, but if I close and open the app again, he cannot.

Thanks

**Comment by raulriera** [comment]
Hey,

it will depend where you are storing them. If its in the temp directory you don't know when the iOS system will clean them up. Maybe you are running out of space?

**Comment by kraw-ios** [comment]
I tried in both temp and custom directory, and I also tried in simulator and real device that has enough space 😄

**Comment by raulriera** [comment]
Strange, can you please reproduce the error in the demo project?

**Comment by kraw-ios** [comment]
@raulriera Sorry for late response, but I has trying to reproduce in an demo project without success! So after some debug I found out that I was using `hashValue` in the fileName of the object and Apple says that this `hashValue` is not the same in every App run.

Sorry about my mistake, I'm closing this issue 😄
